stages:
  - deploy

deploy-pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r docs/. public/
  pages: true
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
